// packages/components/history/[history react17 vite]plain-image-com-ponent/src/components/index.tsx
import './index.module.css'
const PlainImageComponent = ({
        link = 'https://www.baidu.com',
        src = `https://picsum.photos/${Math.floor(Math.random() * 1000)}`,
    } : {link?: string, src?: string} ) => {
    return (
        <a href={link} target="__blank">
            <img src={src} className="my-low-code-plain-components-image" />
        </a>
    )
}

export default PlainImageComponent

// packages/components/history/[history vue-cli]plain-image-com-ponent/src/components/index.vue
<template lang="">
  <a :href="link" target="__blank">
    <img :src="src" class="my-low-code-plain-components-image" />
  </a>
</template>
<script lang="ts" setup>
  import { defineProps, withDefaults } from 'vue'
  const props = withDefaults(defineProps<{
    src: string,
    link: string,
  }>(), {
    link: '',
    src: `https://picsum.photos/${Math.floor(Math.random() * 1000)}`,
  })
</script>
<style lang="stylus">
  .my-low-code-plain-components-image {
    max-width: 100%;
  }
</style>
